### ISSUE TITLE
为什么我这里看gitbook图片全是403呢

### ISSUE THREAD

**Issue by sukaidev** [feelschaotic/AndroidKnowledgeSystem#8]
已经开启全局梯子

**Comment by feelschaotic** [comment]
F12看下控制台报什么错，其实不用梯子也可以访问gitbook的

**Comment by FreeLoopC** [comment]
应该是简书和掘金的图片开了防盗链导致的, 复制图片地址在新窗口可以正常显示

**Comment by feelschaotic** [comment]
> 应该是简书和掘金的图片开了防盗链导致的, 复制图片地址在新窗口可以正常显示

我这边显示正常，你们都无法显示吗，可以截个图看看？如果是的话，我换个图床

**Comment by FreeLoopC** [comment]
@feelschaotic 你本地有缓存所以可以显示, 你可以尝试换个浏览器, 或者用手机打开

**Comment by feelschaotic** [comment]
@sukaidev 你好，重试一下，我已经更换图片图床了

**Comment by isllyend** [comment]
图片依然都是403 chrome/safari +全局梯子

**Comment by gaoRad** [comment]
请问下，你是哪位？我最近收到好几封诸如“图片404”的邮件，是不是你们发错了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"乱"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月7日(星期二) 晚上9:07
收件人:&nbsp;"feelschaotic/AndroidKnowledgeSystem"<AndroidKnowledgeSystem@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [feelschaotic/AndroidKnowledgeSystem] 为什么我这里看gitbook图片全是403呢 (#8)



 
应该是简书和掘金的图片开了防盗链导致的, 复制图片地址在新窗口可以正常显示
  
我这边显示正常，你们都无法显示吗，可以截个图看看？如果是的话，我换个图床

**Comment by gaoRad** [comment]
![image](https://user-images.githubusercontent.com/50544642/71945644-583df400-3202-11ea-866c-13a13a7e19d3.png)
我也出现了无法加载图片的情况

**Comment by CherryLover** [comment]
我不知道你们是什么问题，但是我的电脑最近打开所有 GitHub 上的图片都显示连接服务器失败。

**Comment by Zhangxxl** [comment]
这是github针对Issues区的讨论自动发的，你是不是关注了 https://github.com/feelschaotic/AndroidKnowledgeSystem 这个项目

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: gaoRad<mailto:notifications@github.com>
发送时间: 2020年1月8日 10:28
收件人: feelschaotic/AndroidKnowledgeSystem<mailto:AndroidKnowledgeSystem@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [feelschaotic/AndroidKnowledgeSystem] 为什么我这里看gitbook图片全是403呢 (#8)

请问下，你是哪位？我最近收到好几封诸如“图片404”的邮件，是不是你们发错了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"乱"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月7日(星期二) 晚上9:07
收件人:&nbsp;"feelschaotic/AndroidKnowledgeSystem"<AndroidKnowledgeSystem@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [feelschaotic/AndroidKnowledgeSystem] 为什么我这里看gitbook图片全是403呢 (#8)




应该是简书和掘金的图片开了防盗链导致的, 复制图片地址在新窗口可以正常显示

我这边显示正常，你们都无法显示吗，可以截个图看看？如果是的话，我换个图床

―
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by gaoRad** [comment]
喔喔，是的，谢谢解惑




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhangxxl"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月8日(星期三) 上午10:41
收件人:&nbsp;"feelschaotic/AndroidKnowledgeSystem"<AndroidKnowledgeSystem@noreply.github.com&gt;;
抄送:&nbsp;""<2695532256@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [feelschaotic/AndroidKnowledgeSystem] 为什么我这里看gitbook图片全是403呢 (#8)



这是github针对Issues区的讨论自动发的，你是不是关注了 https://github.com/feelschaotic/AndroidKnowledgeSystem 这个项目 
 
 发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&gt;应用 
 
 发件人: gaoRad<mailto:notifications@github.com&gt; 
 发送时间: 2020年1月8日 10:28 
 收件人: feelschaotic/AndroidKnowledgeSystem<mailto:AndroidKnowledgeSystem@noreply.github.com&gt; 
 抄送: Subscribed<mailto:subscribed@noreply.github.com&gt; 
 主题: Re: [feelschaotic/AndroidKnowledgeSystem] 为什么我这里看gitbook图片全是403呢 (#8) 
 
 请问下，你是哪位？我最近收到好几封诸如“图片404”的邮件，是不是你们发错了 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"乱"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年1月7日(星期二) 晚上9:07 
 收件人:&amp;nbsp;"feelschaotic/AndroidKnowledgeSystem"<AndroidKnowledgeSystem@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [feelschaotic/AndroidKnowledgeSystem] 为什么我这里看gitbook图片全是403呢 (#8) 
 
 
 
 
 应该是简书和掘金的图片开了防盗链导致的, 复制图片地址在新窗口可以正常显示 
 
 我这边显示正常，你们都无法显示吗，可以截个图看看？如果是的话，我换个图床 
 
 ― 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 
 ―

**Comment by feelschaotic** [comment]
> 图片依然都是403 chrome/safari +全局梯子

访问 https://feelschaotic.gitbook.io/android-knowledge-system/  控制台截个图，给我看下图片地址

**Comment by feelschaotic** [comment]
> ![image](https://user-images.githubusercontent.com/50544642/71945644-583df400-3202-11ea-866c-13a13a7e19d3.png)
> 我也出现了无法加载图片的情况

你这个情况是 github 的 CDN 日常抽风，建议加 hosts
```
# GitHub Start 
192.30.253.112    github.com 
192.30.253.119    gist.github.com
151.101.184.133    assets-cdn.github.com
151.101.184.133    raw.githubusercontent.com
151.101.184.133    gist.githubusercontent.com
151.101.184.133    cloud.githubusercontent.com
151.101.184.133    camo.githubusercontent.com
151.101.184.133    avatars0.githubusercontent.com
151.101.184.133    avatars1.githubusercontent.com
151.101.184.133    avatars2.githubusercontent.com
151.101.184.133    avatars3.githubusercontent.com
151.101.184.133    avatars4.githubusercontent.com
151.101.184.133    avatars5.githubusercontent.com
151.101.184.133    avatars6.githubusercontent.com
151.101.184.133    avatars7.githubusercontent.com
151.101.184.133    avatars8.githubusercontent.com
# GitHub End
```

还有什么图片显示不了，可以找图片的 URL，ping 一下拿到 IP 地址，再把 IP 域名添加到 hosts文件中

**Comment by gaoRad** [comment]
> > ![image](https://user-images.githubusercontent.com/50544642/71945644-583df400-3202-11ea-866c-13a13a7e19d3.png)
> > 我也出现了无法加载图片的情况
> 
> 你这个情况是 github 的 CDN 日常抽风，建议加 hosts
> 
> ```
> # GitHub Start 
> 192.30.253.112    github.com 
> 192.30.253.119    gist.github.com
> 151.101.184.133    assets-cdn.github.com
> 151.101.184.133    raw.githubusercontent.com
> 151.101.184.133    gist.githubusercontent.com
> 151.101.184.133    cloud.githubusercontent.com
> 151.101.184.133    camo.githubusercontent.com
> 151.101.184.133    avatars0.githubusercontent.com
> 151.101.184.133    avatars1.githubusercontent.com
> 151.101.184.133    avatars2.githubusercontent.com
> 151.101.184.133    avatars3.githubusercontent.com
> 151.101.184.133    avatars4.githubusercontent.com
> 151.101.184.133    avatars5.githubusercontent.com
> 151.101.184.133    avatars6.githubusercontent.com
> 151.101.184.133    avatars7.githubusercontent.com
> 151.101.184.133    avatars8.githubusercontent.com
> # GitHub End
> ```
> 
> 还有什么图片显示不了，可以找图片的 URL，ping 一下拿到 IP 地址，再把 IP 域名添加到 hosts文件中

已经好了，谢谢

**Comment by isllyend** [comment]
> > 图片依然都是403 chrome / safari +上下梯子
> 
> 访问https://feelschaotic.gitbook.io/android-knowledge-system/ 控制台截个图，给我看下图片地址

![image](https://user-images.githubusercontent.com/15176790/71948345-af47c700-320a-11ea-8bec-cd96bdc6fdc1.png)

**Comment by feelschaotic** [comment]
> > > 图片依然都是403 chrome / safari +上下梯子
> > 
> > 
> > 访问https://feelschaotic.gitbook.io/android-knowledge-system/ 控制台截个图，给我看下图片地址
> 
> ![image](https://user-images.githubusercontent.com/15176790/71948345-af47c700-320a-11ea-8bec-cd96bdc6fdc1.png)
> 无报错

“启动流程和启动模式“这个页面没有图片，当然不会报错呀~，你访问首页 https://feelschaotic.gitbook.io/android-knowledge-system/ 有图片，看看图片能否展示，我换了图床了。

**Comment by isllyend** [comment]
> > > > 图片依然都是403 chrome / safari +上下梯子
> > > 
> > > 
> > > 访问https://feelschaotic.gitbook.io/android-knowledge-system/ 控制台截个图，给我看下图片地址
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/15176790/71948345-af47c700-320a-11ea-8bec-cd96bdc6fdc1.png)
> > 无报错
> 
> “启动流程和启动模式“这个页面没有图片，当然不会报错呀~，你访问首页 https://feelschaotic.gitbook.io/android-knowledge-system/ 有图片，看看图片能否展示，我换了图床了。

![image](https://user-images.githubusercontent.com/15176790/71952956-9a276400-321b-11ea-8c7b-27ee05f38397.png)
一,二章都是没有内容的吗?

**Comment by feelschaotic** [comment]
@isllyend 有内容的，第一章的 组件/webView/JSBridge、组件/webView/加速方案、第二章的设计模式都有内容

**Comment by kingqun** [comment]
我是经常用百度或者360就会出现这种情况，但是切换到chrome就可以正常显示图片了
